### ISSUE TITLE
Landing page title card

### ISSUE THREAD

**Issue by mliu356** [GTBitsOfGood/bright-futures-academy#106]
![image](https://user-images.githubusercontent.com/6752596/54292838-40b3c180-4585-11e9-9b55-10b98f814a44.png)

**Comment by SujeethJinesh** [comment]
I have some questions about this component:

1) Is this a slideshow? Like will the user be seeing a couple of different background updates with time?
2) Is there only going to be 3 of these slides, or can it be dynamic?
3) Will the background image change?
4) If the user clicks on a circle then does that change the slide?

**Comment by thejameswang** [comment]
This is a slide show, the background will change with the image (I believe). There can be more slides, and it is dynamic. The background image can change. If the user clicks the circle, it can change the slide, but that's a functionality that isn't a must.

**Comment by thejameswang** [comment]
CHANGE: "Bright Future" to "Bright Futures"
