### ISSUE TITLE
Landing page Spotlight/Impact section

### ISSUE THREAD

**Issue by mliu356** [GTBitsOfGood/bright-futures-academy#109]
![image](https://user-images.githubusercontent.com/6752596/54292986-83759980-4585-11e9-973a-c131ce46996e.png)

**Comment by SujeethJinesh** [comment]
Couple questions:

1) Do the bubbles lead to some other pages? 
2) Does clicking on "Impact" give you a second view the same as this but with different bubbles?
3) Spotlight seems to be more for people, and Impact seems to be more relevant to the current content of the bubbles. Could you check that this is what Huan intended?
